=== Azure-Samples/dapr-store/cmd/products/spec/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "Product schema",
  "description": "A Dapr Store product",
  "required": [
      "id",
      "name",
      "cost",
      "description",
      "image",
      "onOffer"
  ],
  "additionalProperties": true,
  "properties": {
      "id": {
          "$id": "#/properties/id",
          "type": "string",
          "title": "The id schema",
          "description": "An explanation about the purpose of this instance."
      },
      "name": {
          "$id": "#/properties/name",
          "type": "string",
          "title": "The name schema",
          "description": "An explanation about the purpose of this instance."
      },
      "cost": {
          "$id": "#/properties/cost",
          "type": "number",
          "title": "The cost schema",
          "description": "An explanation about the purpose of this instance."
      },
      "description": {
          "$id": "#/properties/description",
          "type": "string",
          "title": "The description schema",
          "description": "An explanation about the purpose of this instance."

      },
      "image": {
          "$id": "#/properties/image",
          "type": "string",
          "title": "The image schema",
          "description": "An explanation about the purpose of this instance."
      },
      "onOffer": {
          "$id": "#/properties/onOffer",
          "type": "boolean",
          "title": "The onOffer schema",
          "description": "An explanation about the purpose of this instance."
      }
  }
}

=== Azure-Samples/dapr-store/etc/mock-data/products.json
[
  {
    "id": "prd1",
    "name": "Top Hat (6″)",
    "cost": 39.95,
    "description": "Made from 100% wool and quite nice",
    "image": "/img/catalog/1.jpg",
    "onOffer": false
  },
  {
    "id": "prd2",
    "name": "Black & Gold Tie Set",
    "cost": 18,
    "description": "100% hand made silk includes tie, pocket square and cufflinks",
    "image": "/img/catalog/2.jpg",
    "onOffer": true
  },
  {
    "id": "prd3",
    "name": "Paisley Cravat Ascot Tie",
    "cost": 11.2,
    "description": "Black & Red Paisley Cravat",
    "image": "/img/catalog/3.jpg",
    "onOffer": false
  }
]
